# Generated by Django 4.2.5 on 2023-09-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Genero',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ManyToManyField(to='app.genero'),
        ),
    ]
